[uwsgi]
uid = nginx
gid = nginx

processes = 6
master = true
vacuum = True
plugins = python
socket = /home/nginx/www/init/run/uwsgi.sock
chmod-socket = 666

chdir = /home/nginx/www/
wsgi-file = Cgi/wsgi.py

max-requests = 5000				#Respawn processes after serving 5000 requests
reload-on-rss= 100				#Respawn processes if rss memory is higher than 100M
harakiri = 120					#Respawn processes if request was not finished in 120 seconds

log-maxsize = 52428800
log-reopen = true
logfile-chmod = 666
pidfile = /home/nginx/www/init/run/uwsgi.pid
logto = /var/log/uwsgi.log
py-autoreload = 3
